spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?useSSL=true&nullCatalogMeansCurrent=true&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username : root
    password : mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
